URL=http://localhost/Open%20Cart/
Email=gadhaelectronics@gmail.com
Password=tapukepapa
environment=local
first_Name="Jethalal"
last_Name="Gadha"
Address="123/building No.4, mumbai"
City="Mumbai"
Pin="12345678"
Country="India"
State="Maharashtra"
Txt="Lorem Epsum Sring jris and nr"
person2_name="Ipsita"
person2_surname="Das"
person2_email="ipsitadas@gmail.com"
